# Generated by Django 5.2.7 on 2025-10-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
            ],
            options={
                'ordering': ['-date', '-scraped_at'],
            },
        ),
    ]
